spring.application.name=bakery-backend
server.port=8080

# Corrected MySQL URL
spring.datasource.url=jdbc:mysql://saleh-wahabsaleh261204-b880.l.aivencloud.com:19338/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}

# Hibernate and JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
